compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  train_batch_size: 1
  train_micro_batch_size_per_gpu: 1
  fp16:
    enabled: true
  zero_optimization:
    stage: 3
    offload_param:
      device: cpu
      pin_memory: true
    overlap_comm: true
    contiguous_gradients: true
  tensor_parallel:
    tp_size: 4
num_processes: 8
main_training_function: main
mixed_precision: 'fp16'
use_cpu: false